apiVersion: batch/v1
kind: CronJob
metadata:
  name: druid-broker-unique-correlated-flow-viz
  namespace: nsxi-platform-monitoring
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - python3
            - -u
            - /opt/scripts/druid-broker-unique-correlated-flow-viz.py
            image: ipirva/alpine-python@sha256:5d74ce00150cb881526cd9103cad09901375da92ee9fdeac2f52f5dccc0ae991
            imagePullPolicy: IfNotPresent
            name: worker
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /opt/scripts/
              name: druid-broker-unique-correlated-flow-viz
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: default
          serviceAccountName: default
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: druid-broker-unique-correlated-flow-viz
            name: druid-broker-unique-correlated-flow-viz
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false