apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: nsxi-platform-monitoring
data:
  prometheus.rules: |-

  prometheus.yaml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['prometheus-service:8080']
      - job_name: pushgateway
        scrape_interval: 5s
        honor_labels: true
        static_configs:
        - targets: ['pushgateway-service:8080']
          labels:
            pushgateway_instance: pushgateway
