apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: nsxi-platform-monitoring
  labels:
    app: pushgateway
spec:
  selector:
    matchLabels:
      app: pushgateway
  replicas: 1
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:v1.6.2
          ports:
            - containerPort: 9091
              name: pushgateway
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-service
  namespace: nsxi-platform-monitoring
spec:
  selector: 
    app: pushgateway
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9091
      nodePort: 31000