apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsxi-platform-monitoring-sa
  namespace: nsxi-platform-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nsxi-platform-monitoring-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - secrets
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nsxi-platform-monitoring-role-binding
  namespace: nsxi-platform-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nsxi-platform-monitoring-role
subjects:
- kind: ServiceAccount
  name: nsxi-platform-monitoring-sa
  namespace: nsxi-platform-monitoring
---