{
 "title": "NSX Intelligence",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pace Number of Group Compute Relations - groupcomputerelationshipconfig",
     "type": "timeseries",
     "description": "Number of group compute relations\nThis should be less than 1 million and generally less than 100k. \nIf customer is on version older than 4.1.1 and seeing a lot of entries, increase clean up period and manually clean up entries\nUpgrading to 4.1.1 should fix the issue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "pace_groupcomputerelationshipconfig{instance=\"pace\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pace Number of compute objects - normalizedcomputeconfig",
     "type": "timeseries",
     "description": "Number of compute objects\nThis should generally be less than 10000",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "pace_normalizedcomputeconfig{instance=\"pace\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Raw Flow",
     "type": "timeseries",
     "description": "Kakfa message rate for raw_flow\nThis number should be less than 333 for 5 worker nodes or less, and less than 666 for 8 worker nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "kafka_raw_flow{instance=\"kafka\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Over Flow",
     "type": "timeseries",
     "description": "Kakfa message rate for over_flow. This number should generally be less than 999",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "kafka_over_flow{instance=\"kafka\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Minio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minio Total Data Storage Used",
     "type": "timeseries",
     "description": "The sum of the folder sizes should typically be less than 60GB * number of minio pods, where /data/minio/druid using the bulk of storage (>90%). Typically not a concern except for https://kb.vmware.com/s/article/91696 in 4.0.1.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "minio_total_data_storage{instance=\"minio\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Correlated Flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Druid Correlated Flows - correlated_flow_viz unique",
     "type": "timeseries",
     "description": "Get unique correlated_flow_viz number of segments from Druid\nThis number should generally be less than 40 million. \nIf not, please refer to https://kb.vmware.com/s/article/91932 to reduce the uniqueness in flow collection, \nand scale out to 8 worker nodes if possible.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "druid_correlated_flow_viz_unique{instance=\"druid-broker\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Druid Correlated Flows - correlated_flow_viz",
     "type": "timeseries",
     "description": "Get correlated_flow_viz number of segments from Druid\nThis number should be less than 80 million * number of worker nodes. \nIf already breaching, or approaching the threshold, it's recommended to scale out analytics.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "druid_correlated_flow_viz{instance=\"druid-broker\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Config Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Druid Config Object - VM",
     "type": "timeseries",
     "description": "Get total number of config objects in database.\nValues for each config type should be less than 10~20 times the number of object in the system.\nFor example, if there are 5000 VMs in the system, the number of objects should not be more than 100000.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "druid_config_object_VM{instance=\"druid-broker\", job=\"nsxi-platform\", pushgateway_instance=\"pushgateway\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Druid Config Object - NS_GROUP",
     "type": "timeseries",
     "description": "Get total number of config objects in database.\nValues for each config type should be less than 10~20 times the number of object in the system.\nFor example, if there are 5000 VMs in the system, the number of objects should not be more than 100000.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "druid_config_object_NS_GROUP{instance=\"druid-broker\", pushgateway_instance=\"pushgateway\", job=\"nsxi-platform\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Druid Config Object - MANAGER_DFW_RULE",
     "type": "timeseries",
     "description": "Get total number of config objects in database.\nValues for each config type should be less than 10~20 times the number of object in the system.\nFor example, if there are 5000 VMs in the system, the number of objects should not be more than 100000.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "druid_config_object_MANAGER_DFW_RULE",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}