{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TSDB Size - 30 days retention period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "30*24*60*60 * rate(prometheus_tsdb_head_samples_appended_total{type=\"float\", instance=\"prometheus-service:8080\", job=\"prometheus\"}[1d]) * ignoring (type) (rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{instance=\"prometheus-service:8080\", job=\"prometheus\"}[1d]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{instance=\"prometheus-service:8080\", job=\"prometheus\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus samples stored/injested per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"prometheus-service:8080\", job=\"prometheus\", type=\"float\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Physically Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prometheus TSDB WAL Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_storage_size_bytes{instance=\"prometheus-service:8080\", job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}